# Generated by Django 3.1.2 on 2020-12-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='first_chars',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_text',
            field=models.TextField(default='defaultpost'),
            preserve_default=False,
        ),
    ]
